### ISSUE TITLE
Running python svm.py error!

### ISSUE THREAD

**Issue by zhjy8827** [tzaiyang/SpeechEmoRec#4]
Hello,Your code is great！But, I am getting an error when I run the last step.
``
python svm.py
``
display：
``
FileNotFoundError: [Errno 2] No such file or directory: '/home/ldm/datasets/tzaiyang/EMODB/03/train_utterance.npy'
``

Excuse me, where is the problem?

**Comment by zhjy8827** [comment]
I should have no missing steps ..

**Comment by tzaiyang** [comment]
@zhjy8827 
Maybe you should follow *Feature Extracting* again,then be sure there is no error to show and train_utterance.npy will be saved on your path(/home/ldm/datasets/tzaiyang/EMODB/03/)

Hope it works for you!

**Comment by zhjy8827** [comment]
sry.
I found the problem.
In `dtpm.py` need to use 175th and 186th lines of code.
`for i in range(9,10):`  ——> `for i in range(0,len(DataDir.val_speaker)):`
:)
@tzaiyang

**Comment by tzaiyang** [comment]
@zhjy8827 
Oh,Sorry,I forgot it. I comment that line for the convenience of debugging……
o(╯□╰)o
